# Generated by Django 3.0.7 on 2020-08-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterList',
            fields=[
                ('code', models.CharField(choices=[('i', 'i'), ('ii', 'ii'), ('iii', 'iii'), ('iv', 'iv'), ('v', 'v'), ('vi', 'vi'), ('vii', 'vii'), ('viii', 'viii'), ('ix', 'ix'), ('x', 'x'), ('xi', 'xi'), ('xii', 'xii')], max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True, null=True)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('terget_class', models.ManyToManyField(related_name='subject_list', to='college.SemesterList')),
            ],
        ),
    ]
