# Generated by Django 3.0.7 on 2020-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectlist',
            old_name='terget_class',
            new_name='terget_semester',
        ),
        migrations.AlterField(
            model_name='semesterlist',
            name='code',
            field=models.CharField(choices=[('i', 'i'), ('ii', 'ii'), ('iii', 'iii'), ('iv', 'iv'), ('v', 'v'), ('vi', 'vi'), ('vii', 'vii'), ('viii', 'viii')], max_length=4, primary_key=True, serialize=False),
        ),
    ]
