# Generated by Django 3.0.7 on 2020-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20200812_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectlist',
            old_name='terget_semester',
            new_name='target_semester',
        ),
        migrations.RemoveField(
            model_name='subjectlist',
            name='_created',
        ),
        migrations.RemoveField(
            model_name='subjectlist',
            name='_updated',
        ),
        migrations.RemoveField(
            model_name='subjectlist',
            name='discription',
        ),
        migrations.AddField(
            model_name='subjectlist',
            name='target_faculty',
            field=models.ManyToManyField(related_name='subject_list', to='college.Faculty'),
        ),
        migrations.AlterField(
            model_name='subjectlist',
            name='code',
            field=models.CharField(max_length=70),
        ),
    ]
