# Generated by Django 3.1 on 2020-08-12 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDiscussion',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('modified_at', models.DateTimeField(default=datetime.date.today)),
                ('comment', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_title', models.CharField(max_length=100)),
                ('classroom_created_at', models.DateTimeField(default=datetime.date.today)),
                ('classroom_creator', models.CharField(max_length=100)),
                ('classroom_faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_creator', models.CharField(max_length=100)),
            ],
        ),
    ]
