# Generated by Django 3.1 on 2020-09-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.section'),
        ),
    ]
