# Generated by Django 3.1 on 2020-08-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200812_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdiscussion',
            name='file',
        ),
        migrations.AlterField(
            model_name='classdiscussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classdiscussion',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
