# Generated by Django 3.1 on 2020-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200812_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroommember',
            name='is_creator',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
